[package]
description = "Derive macro for the haste crate."
name = "haste-macros"

edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.97"
quote = "1.0.41"
syn = { version = "2.0.110", features = ["full"] }
